import './globals.css'
import Provider from '@/components/Provider'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Provider>
        <body className={inter.className}>
          <main className="flex flex-col bg-gray-200" style={{ height: '100dvh' }}>
            {children}
          </main>
        </body>
      </Provider>
    </html>
  )
}
